[UI.theme]
    font_family = "Inter, sans-serif"

[UI.theme.light]
    background = "#F0F8F7"
    paper = "#FFFFFF"

    [UI.theme.light.primary]
        main = "#4CAF50"
        dark = "#357A38"
        light = "#C8E6C9"

[UI.theme.dark]
    background = "#263238"
    paper = "#37474F"

    [UI.theme.dark.primary]
        main = "#66BB6A"
        dark = "#388E3C"
        light = "#B9F6C"