[UI.theme.light]
    background = "#FAFAFA"
    paper = "#FFFFFF"

    [UI.theme.light.primary]
        main = "#F80061"
        dark = "#980039"
        light = "#FFE7EB"

[UI.theme.dark]
    background = "#FAFAFA"
    paper = "#FFFFFF"

    [UI.theme.dark.primary]
        main = "#F80061"
        dark = "#980039"
        light = "#FFE7EB"